### ISSUE TITLE
Subindex eg: share、diff are Whitelabel Error Page

### ISSUE THREAD

**Issue by huliujun** [yanagishima/yanagishima#362] opened 2021-07-30 12:02 UTC
**Yanagishima version**:

**Presto version**:

**conf/application.yml**:

**JVM version** (`java -version`):

**Server OS version** (`uname -a` if on a Unix-like system):

**Client OS version**:

**Browser**:

**Description of the problem including expected versus actual behavior**:

**Steps to reproduce**:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, hisotry etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1.
 2.
 3.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:

**Comment by ebyhr** [comment] 2021-07-30 12:06
Could you share the steps to reproduce with screenshots?

**Comment by ebyhr** [comment] 2021-07-30 12:44
Let me close this issue because the description is too unclear. Please reopen if you could provide more detailed information.

**Closed by ebyhr** 2021-07-30 12:44 UTC
