### ISSUE TITLE
Can't execute multiple statements in Presto

### ISSUE THREAD

**Issue by greendisc777** [yanagishima/yanagishima#49] opened 2019-01-15 03:55 UTC
**yanagishima version**: 17.0

**presto version**: 0.215

**conf/yanagishima.properties**: 
jetty.port=8090
presto.query.max-run-time-seconds=1800
presto.max-result-file-byte-size=1073741824
presto.datasources=your-presto
presto.coordinator.server.your-presto=http://server:8080
catalog.your-presto=hive
schema.your-presto=default
select.limit=500
audit.http.header.name=some.auth.header
to.values.query.limit=500
check.datasource=false
hive.jdbc.url.your-hive=jdbc:hive2://server:10000/default;
hive.jdbc.user.your-hive=hive
hive.jdbc.password.your-hive=password
hive.query.max-run-time-seconds=3600
hive.query.max-run-time-seconds.your-hive=3600
resource.manager.url.your-hive=http://server:8088
sql.query.engines=presto,hive
hive.datasources=your-hive
hive.max-result-file-byte-size=1073741824
hive.setup.query.path.your-hive=/usr/local/yanagishima/conf/hive_setup_query_your-hive
cors.enabled=false

**JVM version** (`java -version`): openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

**Server OS version** (`uname -a` if on a Unix-like system): CentOS 3.10.0-957.1.3.el7.x86_64 #1 SMP

**Client OS version**

**Browser**: Chrome - Version 71.0.3578.98 (Official Build) (64-bit)

**Description of the problem including expected versus actual behavior**: Cannot execute multiple statements separated by ";"

**Steps to reproduce**: Example:

Please include a *minimal* but *complete* recreation of the problem, including
(e.g.) query execution, bookmark, settings, history etc.  The easier you make for
us to reproduce it, the more likely that somebody will take the time to look at it.

 1. drop table <catalog.schema.tablename>;
 2. create table <catalog.schema.tablename> as select * from <catalog.schema.tablename>;
 3.

**Provide logs (if relevant)**:
	
**Provide screenshots (if relevant)**:
![image](https://user-images.githubusercontent.com/21203002/51157796-196f9b00-1847-11e9-8241-bb1c10c5a21e.png)

**Comment by wyukawa** [comment] 2019-01-15 04:03
Duplicate of #24

**Comment by greendisc777** [comment] 2019-01-15 04:05
I'm not asking for multiple statements for Hive queries. This is pure Presto consuming hive tables.

**Comment by ebyhr** [comment] 2019-08-31 02:11
@greendisc777 Even if we use Presto as the datasource, we can't execute multiple statements for now.

**Comment by greendisc777** [comment] 2019-08-31 03:11
The Presto CLI supports executing multiple statements in a file with each line terminated by ";"

**Comment by ebyhr** [comment] 2019-08-31 03:33
Yes, I knew it. The hard point isn't parsing the queries. As mentioned in #24, simply it requires many changes. Please imagine multiple SELECT queries.

**Closed** 2021-04-29 07:38 UTC
Labels: enhancement
